# Generated by Django 4.2.24 on 2025-09-13 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(blank=True, max_length=100, verbose_name='Тип игры')),
                ('game_name', models.CharField(blank=True, max_length=150, verbose_name='Название игры')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('paused', 'Пауза'), ('finished', 'Завершена'), ('aborted', 'Прервана')], db_index=True, default='active', max_length=16, verbose_name='Статус')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Актуальная (для продолжения)')),
                ('current_cell', models.IntegerField(default=0, verbose_name='Текущая клетка')),
                ('last_move_number', models.IntegerField(default=0, verbose_name='№ последнего хода')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='players.player')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('move_number', models.PositiveIntegerField(verbose_name='№ хода')),
                ('rolled', models.PositiveSmallIntegerField(default=0, verbose_name='Бросок кубика')),
                ('from_cell', models.IntegerField(default=0, verbose_name='С клетки')),
                ('to_cell', models.IntegerField(default=0, verbose_name='На клетку')),
                ('event_type', models.CharField(choices=[('normal', 'Обычный ход'), ('snake', 'Змея'), ('ladder', 'Стрела/лестница'), ('bonus', 'Бонус'), ('penalty', 'Штраф')], default='normal', max_length=16, verbose_name='Событие')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('state_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Состояние после хода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
            ],
            options={
                'ordering': ('move_number',),
                'indexes': [models.Index(fields=['game', 'move_number'], name='games_move_game_id_ebaa0c_idx'), models.Index(fields=['-created_at'], name='games_move_created_a05eb3_idx')],
                'unique_together': {('game', 'move_number')},
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player', 'is_active', '-updated_at'], name='games_game_player__12450a_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player', 'status', '-updated_at'], name='games_game_player__3640e7_idx'),
        ),
    ]
