# Generated by Django 4.2.24 on 2025-09-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=150, verbose_name='Никнейм в Telegram')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('bot_token', models.CharField(blank=True, max_length=255, verbose_name='Токен бота')),
                ('main_status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('banned', 'Заблокирован')], default='active', max_length=16, verbose_name='Главный статус')),
                ('payment_status', models.CharField(choices=[('none', 'Нет оплаты'), ('pending', 'Ожидает'), ('paid', 'Оплачено'), ('refunded', 'Возврат')], default='none', max_length=16, verbose_name='Статус оплаты')),
                ('player_type', models.CharField(choices=[('free', 'Бесплатный'), ('trial', 'Триал'), ('premium', 'Премиум'), ('admin', 'Админ')], default='free', max_length=16, verbose_name='Тип игрока')),
                ('game_type', models.CharField(blank=True, max_length=100, verbose_name='Тип игры')),
                ('game_name', models.CharField(blank=True, max_length=150, verbose_name='Название игры')),
            ],
        ),
    ]
